# Generated by Django 4.2.1 on 2023-05-11 11:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buhgalteriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buhgalteriya', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Бухгалтер',
                'verbose_name_plural': 'Бухгалтеры',
            },
        ),
        migrations.CreateModel(
            name='Dekanat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dekanat', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представители деканата',
                'verbose_name_plural': 'Представители деканата',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('flow', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(1950)])),
            ],
            options={
                'verbose_name': 'Направления',
                'verbose_name_plural': 'Направлении',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('description', models.TextField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.direction')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.faculty')),
                ('teachers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
            options={
                'verbose_name': 'Вид образовательного заведения',
                'verbose_name_plural': 'Виды образовательного заведения',
            },
        ),
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kafedra', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представитель кафедры',
                'verbose_name_plural': 'Представители кафедры',
            },
        ),
        migrations.CreateModel(
            name='MezhdunarodnyiOtdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mezhdunarodnyi_otdel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представитель международного отдела',
                'verbose_name_plural': 'Представители международного отдела',
            },
        ),
        migrations.CreateModel(
            name='OtdelKadrovPPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_otdel_kadrov_pps', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представитель отдела кадров ППС',
                'verbose_name_plural': 'Представители отдела кадров ППС',
            },
        ),
        migrations.CreateModel(
            name='OtdelKadrovUchashiesya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_otdel_kadrov_studentov', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представитель отдела кадров студентов',
                'verbose_name_plural': 'Представители отдела кадров студентов',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Prepodavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_prepodavatel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
            },
        ),
        migrations.CreateModel(
            name='PriemnayaKomissiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_priemnaya_komisiya', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представитель приемной комиссии',
                'verbose_name_plural': 'Представители приемной комиссии',
            },
        ),
        migrations.CreateModel(
            name='Roditeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_roditel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='UchebnyiOtdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_uchebnyi_otdel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представитель учебногот отдела',
                'verbose_name_plural': 'Представитель учебногот отдела',
            },
        ),
        migrations.CreateModel(
            name='UMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_umk', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представитель учебно методического комполекса',
                'verbose_name_plural': 'Представитель учебно методического комполекса',
            },
        ),
        migrations.CreateModel(
            name='VtoroiOtdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vtoroi_otdel', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Представтель воторого отдела',
                'verbose_name_plural': 'Представтель воторого отдела',
            },
        ),
        migrations.CreateModel(
            name='UZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('adress', models.CharField(max_length=255)),
                ('faculties', models.ManyToManyField(to='server.faculty')),
                ('uchrezhdenie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.education')),
            ],
            options={
                'verbose_name': 'Учебное заведение',
                'verbose_name_plural': 'Учебные заведения',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student', models.BooleanField(default=True)),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direction_students', to='server.direction')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=12)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.direction')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписании',
                'unique_together': {('direction', 'years')},
            },
        ),
        migrations.CreateModel(
            name='DisciplineCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.PositiveIntegerField()),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.discipline')),
            ],
            options={
                'verbose_name': 'Кредитация дисциплины',
                'verbose_name_plural': 'Кредитаци дисциполны',
            },
        ),
        migrations.CreateModel(
            name='DesciplineShedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('day', models.CharField(max_length=10)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.disciplinecredits')),
                ('shedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinesh', to='server.schedule')),
            ],
            options={
                'verbose_name': 'Расписание дисциплины',
                'verbose_name_plural': 'Расписании дисциплины',
            },
        ),
    ]
