# Generated by Django 4.2.1 on 2023-05-13 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='user',
            field=models.ManyToManyField(related_name='users_disciplines', to=settings.AUTH_USER_MODEL),
        ),
    ]
