# Generated by Django 4.2.1 on 2023-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='uz',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
